### ISSUE TITLE
Add letter "Z"

### ISSUE THREAD

**Issue by cquon** [cquon/block-letters#23]

**Comment by TJScalzo** [comment]
I would like to do this letter.

**Comment by TJScalzo** [comment]
It seems @joshalling has done this letter anyway. Oh well, I guess I'll find another one.

**Comment by joshalling** [comment]
@TJScalzo Sorry, I didn't see that you had already claimed this one.

**Comment by TJScalzo** [comment]
@joshalling No worries, there are plenty of letters in the alphabet.
